// BLOC 1 - Role du fichier.
// Ce fichier centralise des constantes backend pour errorCodes.
// Point de vigilance: modifier avec prudence car ce fichier peut etre importe par plusieurs modules.

const ERROR_CODES = Object.freeze({
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_APPROVED: 'PRODUCT_NOT_APPROVED',
  STOCK_INSUFFICIENT: 'STOCK_INSUFFICIENT',
  FIFO_LOT_INSUFFICIENT: 'FIFO_LOT_INSUFFICIENT',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_STATUS_FORBIDDEN_SELF: 'USER_STATUS_FORBIDDEN_SELF',
  USER_STATUS_FORBIDDEN_ROLE: 'USER_STATUS_FORBIDDEN_ROLE',
  USER_STATUS_REASON_REQUIRED: 'USER_STATUS_REASON_REQUIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = {
  ERROR_CODES,
};

