const PERMISSIONS = Object.freeze({
  PRODUCT_READ: 'product.read',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_VALIDATE: 'product.validate',
  PRODUCT_DELETE: 'product.delete',
  CATEGORY_MANAGE: 'category.manage',
  STOCK_ENTRY_CREATE: 'stock.entry.create',
  STOCK_EXIT_CREATE: 'stock.exit.create',
  STOCK_ENTRY_UPDATE: 'stock.entry.update',
  STOCK_EXIT_UPDATE: 'stock.exit.update',
  STOCK_ENTRY_CANCEL: 'stock.entry.cancel',
  STOCK_EXIT_CANCEL: 'stock.exit.cancel',
  ATTACHMENT_UPLOAD: 'attachment.upload',
  REQUEST_CREATE: 'request.create',
  REQUEST_READ_OWN: 'request.read.own',
  REQUEST_READ_ALL: 'request.read.all',
  REQUEST_VALIDATE: 'request.validate',
  SUPPLIER_MANAGE: 'supplier.manage',
  PURCHASE_ORDER_MANAGE: 'purchase_order.manage',
  HISTORY_READ: 'history.read',
  SECURITY_AUDIT_READ: 'security_audit.read',
  USER_MANAGE: 'user.manage',
  SESSION_MONITOR: 'session.monitor',
  SESSION_REVOKE: 'session.revoke',
  INVENTORY_MANAGE: 'inventory.manage',
});

// Labels/categories for Admin console (RBAC UI).
const PERMISSION_META = Object.freeze({
  [PERMISSIONS.PRODUCT_READ]: { label: 'Lire produits', area: 'produits' },
  [PERMISSIONS.PRODUCT_CREATE]: { label: 'Créer produits', area: 'produits' },
  [PERMISSIONS.PRODUCT_UPDATE]: { label: 'Modifier produits', area: 'produits' },
  [PERMISSIONS.PRODUCT_VALIDATE]: { label: 'Valider produits', area: 'produits' },
  [PERMISSIONS.PRODUCT_DELETE]: { label: 'Supprimer produits', area: 'produits' },
  [PERMISSIONS.CATEGORY_MANAGE]: { label: 'Gérer catégories', area: 'catalogue' },
  [PERMISSIONS.STOCK_ENTRY_CREATE]: { label: 'Créer entrées stock', area: 'stock' },
  [PERMISSIONS.STOCK_EXIT_CREATE]: { label: 'Créer sorties stock', area: 'stock' },
  [PERMISSIONS.STOCK_ENTRY_UPDATE]: { label: 'Modifier entrées stock', area: 'stock' },
  [PERMISSIONS.STOCK_EXIT_UPDATE]: { label: 'Modifier sorties stock', area: 'stock' },
  [PERMISSIONS.STOCK_ENTRY_CANCEL]: { label: 'Annuler entrées stock', area: 'stock' },
  [PERMISSIONS.STOCK_EXIT_CANCEL]: { label: 'Annuler sorties stock', area: 'stock' },
  [PERMISSIONS.ATTACHMENT_UPLOAD]: { label: 'Importer fichiers', area: 'fichiers' },
  [PERMISSIONS.REQUEST_CREATE]: { label: 'Créer demandes', area: 'demandes' },
  [PERMISSIONS.REQUEST_READ_OWN]: { label: 'Lire ses demandes', area: 'demandes' },
  [PERMISSIONS.REQUEST_READ_ALL]: { label: 'Lire toutes demandes', area: 'demandes' },
  [PERMISSIONS.REQUEST_VALIDATE]: { label: 'Valider/Rejeter demandes', area: 'demandes' },
  [PERMISSIONS.SUPPLIER_MANAGE]: { label: 'Gérer fournisseurs', area: 'fournisseurs' },
  [PERMISSIONS.PURCHASE_ORDER_MANAGE]: { label: 'Gérer commandes fournisseurs', area: 'fournisseurs' },
  [PERMISSIONS.HISTORY_READ]: { label: 'Consulter historique', area: 'audit' },
  [PERMISSIONS.SECURITY_AUDIT_READ]: { label: 'Consulter audit sécurité', area: 'admin_it' },
  [PERMISSIONS.USER_MANAGE]: { label: 'Gérer utilisateurs', area: 'admin_it' },
  [PERMISSIONS.SESSION_MONITOR]: { label: 'Surveiller sessions', area: 'admin_it' },
  [PERMISSIONS.SESSION_REVOKE]: { label: 'Révoquer sessions', area: 'admin_it' },
  [PERMISSIONS.INVENTORY_MANAGE]: { label: 'Gérer inventaires', area: 'inventaire' },
});

const ROLE_PERMISSIONS = Object.freeze({
  demandeur: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ_OWN,
    PERMISSIONS.HISTORY_READ,
  ]),
  magasinier: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.STOCK_ENTRY_CREATE,
    PERMISSIONS.STOCK_EXIT_CREATE,
    PERMISSIONS.STOCK_ENTRY_UPDATE,
    PERMISSIONS.STOCK_EXIT_UPDATE,
    PERMISSIONS.STOCK_ENTRY_CANCEL,
    PERMISSIONS.STOCK_EXIT_CANCEL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.REQUEST_READ_ALL,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.PURCHASE_ORDER_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
  ]),
  responsable: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_VALIDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.STOCK_ENTRY_CREATE,
    PERMISSIONS.STOCK_EXIT_CREATE,
    PERMISSIONS.STOCK_ENTRY_UPDATE,
    PERMISSIONS.STOCK_EXIT_UPDATE,
    PERMISSIONS.STOCK_ENTRY_CANCEL,
    PERMISSIONS.STOCK_EXIT_CANCEL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.REQUEST_READ_ALL,
    PERMISSIONS.REQUEST_VALIDATE,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.SUPPLIER_MANAGE,
    PERMISSIONS.PURCHASE_ORDER_MANAGE,
    PERMISSIONS.INVENTORY_MANAGE,
  ]),
  admin: new Set([
    // Admin (informatique) : role purement technique.
    // Il ne doit pas intervenir dans les flux metier (stock/produits/demandes).
    PERMISSIONS.SECURITY_AUDIT_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.SESSION_MONITOR,
    PERMISSIONS.SESSION_REVOKE,
  ]),
});

function hasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role];
  return Boolean(perms && perms.has(permission));
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  PERMISSION_META,
};
