const PERMISSIONS = Object.freeze({
  PRODUCT_READ: 'product.read',
  PRODUCT_CREATE: 'product.create',
  PRODUCT_UPDATE: 'product.update',
  PRODUCT_VALIDATE: 'product.validate',
  CATEGORY_MANAGE: 'category.manage',
  STOCK_ENTRY_CREATE: 'stock.entry.create',
  STOCK_EXIT_CREATE: 'stock.exit.create',
  STOCK_ENTRY_UPDATE: 'stock.entry.update',
  STOCK_EXIT_UPDATE: 'stock.exit.update',
  STOCK_ENTRY_CANCEL: 'stock.entry.cancel',
  STOCK_EXIT_CANCEL: 'stock.exit.cancel',
  ATTACHMENT_UPLOAD: 'attachment.upload',
  REQUEST_CREATE: 'request.create',
  REQUEST_READ_OWN: 'request.read.own',
  REQUEST_READ_ALL: 'request.read.all',
  HISTORY_READ: 'history.read',
  SECURITY_AUDIT_READ: 'security_audit.read',
  USER_MANAGE: 'user.manage',
  SESSION_MONITOR: 'session.monitor',
  SESSION_REVOKE: 'session.revoke',
});

const ROLE_PERMISSIONS = Object.freeze({
  demandeur: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.REQUEST_CREATE,
    PERMISSIONS.REQUEST_READ_OWN,
    PERMISSIONS.HISTORY_READ,
  ]),
  magasinier: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.STOCK_ENTRY_CREATE,
    PERMISSIONS.STOCK_EXIT_CREATE,
    PERMISSIONS.STOCK_ENTRY_UPDATE,
    PERMISSIONS.STOCK_EXIT_UPDATE,
    PERMISSIONS.STOCK_ENTRY_CANCEL,
    PERMISSIONS.STOCK_EXIT_CANCEL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.REQUEST_READ_ALL,
    PERMISSIONS.HISTORY_READ,
  ]),
  responsable: new Set([
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_VALIDATE,
    PERMISSIONS.CATEGORY_MANAGE,
    PERMISSIONS.STOCK_ENTRY_CREATE,
    PERMISSIONS.STOCK_EXIT_CREATE,
    PERMISSIONS.STOCK_ENTRY_UPDATE,
    PERMISSIONS.STOCK_EXIT_UPDATE,
    PERMISSIONS.STOCK_ENTRY_CANCEL,
    PERMISSIONS.STOCK_EXIT_CANCEL,
    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.REQUEST_READ_ALL,
    PERMISSIONS.HISTORY_READ,
    PERMISSIONS.SECURITY_AUDIT_READ,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.SESSION_MONITOR,
    PERMISSIONS.SESSION_REVOKE,
  ]),
});

function hasPermission(role, permission) {
  const perms = ROLE_PERMISSIONS[role];
  return Boolean(perms && perms.has(permission));
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
};
